- hosts: all
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install docker-py
      pip:
        name: docker-py
        version: 1.8.0
        state: present

    - name: Run container
      community.docker.docker_container:
        name: App
        image: redmine
        ports:
        - "5000:3000"
        env:
          REDMINE_DB_POSTGRES: "{{ db_host }}"
          REDMINE_DB_PORT: "{{ db_port }}"
          REDMINE_DB_USERNAME: "{{ db_user }}"
          REDMINE_DB_DATABASE: "{{ db_name }}"
          REDMINE_DB_PASSWORD: "{{ db_password }}"
          
