- name: Install pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: Install docker-py
  pip:
    name: docker-py
    version: "{{ docker_py_version }}"
    state: present
